version: '3.9'

# Common context for all services
x-common-dev: &consumer-build
  build:
    context: .
    dockerfile: consumer/Dockerfile
  restart: always
  environment:
    KAFKA_SERVER: kafka:9092
    KAFKA_GROUP: Messages
    MESSAGE_TOPIC: messagetopic
    MONGODB_ENDPOINT: mongodb://mongo:27017
    MONGODB_DBNAME: messagesDB
    MONGODB_COLLECTION: messagesColl
  depends_on:
    - mongo
    - kafka
    - producer

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper:/data
  
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
  
  producer: 
    build: 
      context: .
      dockerfile: producer/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      APP_PORT: :8080
      KAFKA_SERVER: kafka:9092
      KAFKA_GROUP: Messages
      MESSAGE_TOPIC: messagetopic
    depends_on:
      - kafka
      - zookeeper

  consumer1: 
    <<: *consumer-build

  consumer2:
    <<: *consumer-build
  
  consumer3:
    <<: *consumer-build